### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bee-san** [bee-san/CyberFork#10]
- [ ] change cyberchef to cyberfork name
- [ ] take in some more pull requests
- [ ] write blog post
